import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import Navber from "@/components/Shared/Navber";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navber></Navber>
          <div className="container mx-auto mt-3">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
